# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='year_issue',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stockcomposition',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplycomposition',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
