# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksshop', '0002_auto_20170216_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='booksshop.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, to='booksshop.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rewards',
            field=models.ManyToManyField(blank=True, to='booksshop.Reward'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='booksshop.Book'),
        ),
    ]
