# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksshop', '0003_auto_20170216_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stock',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booksshop.Stock'),
        ),
    ]
