# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksshop', '0004_auto_20170216_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booksshop.Stock'),
        ),
    ]
